### ISSUE TITLE
Can't get dexy to work

### ISSUE THREAD

**Issue by nikhilbhardwaj** [dexy/dexy#6]
I'm running arch linux. Here's the error I get with dexy version
Traceback (most recent call last):
  File "/usr/bin/dexy", line 9, in <module>
    load_entry_point('dexy==0.5.2', 'console_scripts', 'dexy')()
  File "/usr/lib/python3.2/site-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.2/site-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.2/site-packages/pkg_resources.py", line 1990, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python3.2/site-packages/dexy-0.5.2-py3.2.egg/dexy/commands.py", line 81
    print "Please run '%s setup' first to create the directories dexy needs to work with" % PROG
                                                                                        ^
SyntaxError: invalid syntax

**Comment by ananelson** [comment]
This is because you are running Python 3.X and Dexy currently only runs on Python 2.6 or 2.7. Can you install Python 2?

**Comment by nikhilbhardwaj** [comment]
Thanks, yes I installed python2 and now it works fine.
